let topicFilterSidebar = {
    css: [
        "CSS (569)",
        "HTML (210)",
        "Web Development (24)",
        "JavaScript (21)",
        "Web Design (14)",
        "Front End Web Development (9)",
        "Bootstrap (7)",
        "Sass (6)",
        "PHP (programming language) (5)",
        "Responsive Design (4)",
        "Animation (2)",
        "CSS Grid (2)",
        "Dreamweaver (2)",
        "CSS Animations (2)",
        "React JS (2)",
        "jQuery (2)",
        "Web Forms (1)",
        "Online Presence (1)",
        "API (1)",
        "Cartoon Drawing (1)",
        "Laravel (1)",
        "Adobe Photoshop (1)",
        "Coding For Kids (1)",
        "Developer Tools (1)",
        "Vue JS (1)",
    ],
    javascript: [
        "JavaScript (1,320)",
        "HTML (36)",
        "Web Development (21)",
        "CSS (21)",
        "React JS (15)",
        "jQuery (12)",
        "Node.Js (9)",
        "PHP (programming language) (9)",
        "ECMAscript (7)",
        "Typescript (7)",
        "Front End Web Development (6)",
        "Object-Oriented Programming (OOP) (5)",
        "Ajax (programming) (5)",
        "Vue JS (5)",
        "Data Structures (5)",
        "Game Development Fundamentals (4)",
        "Functional Programming (4)",
        "Angular (4)",
        "Algorithms (4)",
        "Bootstrap (4)",
        "Programming Fundamentals (4)",
        "JSON (4)",
        "Java (3)",
        "Python (3)",
        "MySQL (3)",
    ],
    "react": [
        "React JS (819)",
        "Redux Framework (28)",
        "JavaScript (15)",
        "React Hooks (11)",
        "MERN Stack (7)",
        "Node.Js (6)",
        "Front End Web Development (6)",
        "Next.js (6)",
        "Web Development (5)",
        "Go (programming language) (5)",
        "Typescript (5)",
        "GraphQL (5)",
        "Firebase (4)",
        "Angular (3)",
        "Bootstrap (3)",
        "Vue JS (3)",
        "Spring Boot (3)",
        "Full Stack Web Development (3)",
        "Web App Development (2)",
        "CSS (2)",
        "Test-Driven Development (TDD) (2)",
        "MongoDB (2)",
        "Redux (JavaScript library) (2)",
        "Software Development (2)",
        "Meteor Framework (2)",
    ],
    "nextjs": [
        "Next.js (152)",
        "React JS (6)",
        "Three.JS (1)",
        "Typescript (1)",
        "Amazon S3 (1)",
        "Firebase (1)",
        "CSS Grid (1)",
        "Stripe Payments Platform (1)",
        "GraphQL (1)",
    ]

}